# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    client:
        serviceUrl:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        maximumPoolSize: 10
        url: jdbc:h2:file:./target/h2db/db/frontend;DB_CLOSE_DELAY=-1
        username: frontend
        password:
